[tracing.filters]
default = "debug"
hyper = "info"
sqlx = "info"
# tantivy = "warn"

[http]
# address = "0.0.0.0"
port = 8080

[http.admin.auth]
username = "username"
password = "password"

[http.api1.sheet]
limit.default = 100
limit.max = 500
limit.depth = 2
# TODO: should this be shared with search eventually, or nah?
filter.exdschema.list = "Name,Singular,Icon"

[read.language]
default = "en"
# This default configuration is set up for the global game client, which does not ship Chinese or Korean data.
exclude = ["chs", "cht", "kr"]

[version]
interval = 3600 # 1 hour
directory = "versions"
repositories = [
  "4e9a232b", # ffxiv
  "6b936f08", # ex1 (hw)
  "f29a3eb2", # ex2 (stb)
  "859d0e24", # ex3 (shb)
  "1bf99b87", # ex4 (ew)
  "6cfeab11", # ex5 (dt)
]

[version.thaliak]
endpoint = "https://thaliak.xiv.dev/graphql/2022-08-14"

# Thaliak bugged out and failed to link between the last delta patch, and the history patches, at 7.0.
# This is just a manual specification of those links to restore the patch chain.
[version.thaliak.overrides]
4e9a232b = { "2024.05.31.0000.0000" = "H2024.05.31.0000.0000z" }
6b936f08 = { "2024.05.31.0000.0000" = "H2024.05.31.0000.0000d" }
f29a3eb2 = { "2024.05.31.0000.0000" = "H2024.05.31.0000.0000e" }
859d0e24 = { "2024.05.31.0000.0000" = "H2024.05.31.0000.0000g" }
1bf99b87 = { "2024.05.31.0000.0000" = "H2024.05.31.0000.0000i" }

[version.patch]
directory = "patches"
concurrency = 4
user_agent = "FFXIV PATCH CLIENT"

[schema]
default = "exdschema"
interval = 3600       # 1 hour

[schema.exdschema]
default = "HEAD"
remote = "https://github.com/xivdev/EXDSchema.git"
directory = "exdschema"

[search.pagination]
limit_default = 100
limit_max = 500

[search.sqlite]
directory = "search"
max_batch_size = 50

# [search.tantivy]
# directory = "search"
# memory = 52428800    # 50MiB

# [search.tantivy.cursor]
# ttl = 3600 # 1 hour
# tti = 300  # 5 minutes
